/* automatically generated by rust-bindgen */

pub type callback_func =
    ::std::option::Option<unsafe extern "C" fn(usr: *mut ::std::os::raw::c_void)>;
extern "C" {
    pub fn register_callback(f: callback_func, usr: *mut ::std::os::raw::c_void);
}
